---
title: "Homework_3"
author: "Phoebe"
date: "2023-02-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## Regular Expressions

Problem Number | Find                                                  | Replace 
---------------|-------------------------------------------------------|--------
1              |`\s{2,}`                                               |`,`
2              |`(\w+),\s(\w+),\s(.+)`                                 |`\2 \1 (\3)`
3              |`\s(\d)`                                               |`\n\1`
4              |`(\d{4})(\s.*)(\.\w*)`                                 |`\2_\1\3`
5              |`(^\w)(\w*\,)(\w*)(.*)(\d*\.\d*)(.*)`                  |`\1_\3\6`
6              |`(^\w)(\w*\,)(\w{4})(.*)(\d*\.\d*)(.*)`                |`\1_\3\6`
7              |`(^\w{3})(\w*\,)(\w{3})(\w*)(\,)(\d*\.\d*)(\,)(\d*)`   |`\1\3\5 \6\7 \8`

#### Explainations
1. Remove spaces between columns by capturing spaces if there are 2 or more, and replacing them with a comma.
2. Broke up each name/university into captures and reordered them using the replace feature and putting the capture of the university name in parentheses.
3. Identify spaces before numbers and replace with line break.
4. Break up using captures into number, song name, and ".mp3" and reorganize and add underscore
5. Capture the first letter and use captures to break up the line word by word. Use replace to remove unwanted characters
6. Rather than using `\w*` and capturing all characters of the second word, I used replace to specify only the first 4 words
7. ^^ same as 6, but specifying 3 letters for both the first and second word.

