---
title: "Homework 4"
author: "Phoebe"
date: "2023-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.

### 1a.
```{r}
x <- 1.1

a <- 2.2

b <- 3.3
```
### 1b. 
``` {r}
z <- (x^a)^b

print(z)
```
### 1c. 
```{r}
z <- 3*(x^3)+2*(x^2)+1

print(z)
```

# 2.

### 2a. 
```{r}
a <- rep(1:8)

b <- rep(7:1)

c(a,b)
```
### 2b. 
```{r}
a <- seq(1, 5)

rep(a, times = a)
```
### 2c. 
```{r}
a <- seq(1, 5)

b <- seq(5, 1)

rep(b, times = a)
```

# 3.

### 3a. 
```{r}
x <- runif(1, min = 0, max = 100)

y <- runif(1, min = 0, max = 100)

# y/sin(b) = x/cos(b)

t <- atan(y/x)

r <- cos(t)/x

print(r)
print(t)
```

# 4.

```{r}
queue <- c("sheep", "fox", "owl", "ant")
print(queue)
queueA <- c(queue, "serpent")
print(queueA)
queueB <- c(queueA, "sheep")
print(queueB)
queueC <- c("donkey", queueB)
print(queueC)
queueD <- c(gsub("serpent", "", queueC))
print(queueD)
queueE <- c(gsub("owl", "" , queueD))
print(queueE)
queueF <- append(queueE, "aphid", after = +5)
print(queueF)
queueG <- match("aphid", queueF)
print(queueG)

```

# 5.
```{r}

a <- (1:100)
b <- a %% 2 == 0 
c <- a %% 3 == 0
d <- a %% 7 == 0
answer <- c(b | c | d)
print(answer)

```






